# CC := g++
# SRCDIR := src
# BUILDDIR := build
# TARGET := bin/boolex_test
 
# SRCEXT := cpp
# SOURCES := $(shell find $(SRCDIR) -type f -name *.$(SRCEXT))
# OBJECTS := $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.o))
# CFLAGS := -g -Wall -std=c++11
# LIB := -L lib
# INC := -I include

# $(TARGET): $(OBJECTS)
# 	@mkdir -p $(@D)
# 	@echo " Linking..."
# 	@echo " $(CC) $^ -o $(TARGET) $(LIB)"; $(CC) $^ -o $(TARGET) $(LIB)

# $(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
# 	@mkdir -p $(@D)
# 	@echo " $(CC) $(CFLAGS) $(INC) -c -o $@ $<"; $(CC) $(CFLAGS) $(INC) -c -o $@ $<

# clean:
# 	@echo " Cleaning..."; 
# 	@echo " $(RM) -r $(BUILDDIR) $(TARGET)"; $(RM) -r $(BUILDDIR) $(TARGET)

# .PHONY: clean